PIC-2733
ministryofjustice/court-case-service pull request #1051
Opened 2023-03-21 07:22 UTC by vb-moj

. Added script to create case marker entity.
. Added case marker entity to hearing.
. Updated tests.

2023-03-21 09:45 UTC, rschallapalli requested changes

2023-03-21 09:45 UTC, rschallapalli commented on src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/HearingEntity.java
Can we check if the case markers should be associated with CourtCase instead of Hearing?
If a new hearing comes and there are no case markers are we not supposed to show the case markers when the user view the summary?  
The implementation might be right but just want to clarify.

2023-03-21 09:49 UTC, vb-moj commented on src/main/java/uk/gov/justice/probation/courtcaseservice/jpa/entity/HearingEntity.java
Good point but I am not sure. Will check with Tony.

2023-03-21 17:31 UTC, rschallapalli commented on src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/Plea.java
> +import uk.gov.justice.probation.courtcaseservice.jpa.entity.PleaEntity;
Unused import?

2023-03-21 17:31 UTC, rschallapalli commented on src/main/java/uk/gov/justice/probation/courtcaseservice/controller/model/Verdict.java
> +import uk.gov.justice.probation.courtcaseservice.jpa.entity.VerdictEntity;
Unused import?

2023-03-21 17:31 UTC, rschallapalli commented on src/main/java/uk/gov/justice/probation/courtcaseservice/service/ImmutableCourtCaseService.java
> +        //courtCaseEntity.addCaseMarkers(updatedHearing.getCourtCase().getCaseMarkers());
Can be removed?

2023-03-22 08:49 UTC, rschallapalli approved these changes

2023-03-22 08:51 UTC, merged