PIC-1932 adding case source to telemetry
ministryofjustice/court-case-service pull request #795
Opened 2022-05-16 13:47 UTC by rschallapalli

2022-05-16 14:05 UTC, jhevans requested changes
One tiny and probably slightly pernickety request 😆

2022-05-16 14:08 UTC, rschallapalli commented on src/main/java/uk/gov/justice/probation/courtcaseservice/service/TelemetryService.java
> +                    properties.put("courtCaseSource", sourceType.name());
👍

2022-05-16 14:51 UTC, rschallapalli commented on src/main/java/uk/gov/justice/probation/courtcaseservice/service/TelemetryService.java
> +                    properties.put("courtCaseSource", sourceType.name());
Updated, thanks

2022-05-17 09:28 UTC, jhevans approved these changes

2022-05-17 09:28 UTC, merged